name: Check links

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linkcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
